Use net.ErrClosed
nhooyr/websocket pull request #303
Opened 2021-05-19 21:53 UTC by emersion

Go 1.16 has introduced net.ErrClosed, which should be returned/wrapped when an
I/O call is performed on a network connection which has already been closed.
This is useful to avoid cluttering logs with messages like "failed to close
WebSocket: already wrote close".

Closes: https://github.com/nhooyr/websocket/issues/286

2021-05-20 07:36 UTC, Antonboom commented
Like!

2021-06-01 08:46 UTC, emersion commented
Hi @nhooyr, any chance to get this reviewed? Thanks!

2021-06-11 08:24 UTC, emersion commented
Ping @nhooyr, would you have the time to have a look?

2021-06-17 04:03 UTC, nhooyr commented
Sorry for the delay I'm on a rather long sabbatical right now. Will review when I'm back by the end of this month!

2021-06-17 08:57 UTC, emersion commented
Cool! No problem, take your time :)

2021-08-31 06:20 UTC, Antonboom commented
Any news?

2021-09-13 12:22 UTC, emersion commented
Hi again @nhooyr, any chance to get this reviewed?

2021-09-13 15:22 UTC, bokunodev reviewed
both `close__go113.go` and `close__go116.go` has build tag
`// +build !go1.16`

2021-09-19 13:21 UTC, nhooyr commented
> Hi again @nhooyr, any chance to get this reviewed?

Sorry @emersion my sabbatical continues until at least mid October. Apologies for the delay and the broken promise above but I'm dealing with some personal stuff right now and was hoping to be back sooner.

I could merge this as is into master as I don't see anything wrong with it but I can't do any sort of release without dealing with #256 first which will take substantial effort. So I'd prefer to leave this PR open as is until I'm back.

2021-09-19 13:21 UTC, nhooyr approved these changes

2021-09-19 13:38 UTC, emersion commented
> Apologies for the delay and the broken promise above but I'm dealing with some personal stuff right now and was hoping to be back sooner.

No problem, thanks for having a look.

> I could merge this as is into master as I don't see anything wrong with it but I can't do any sort of release without dealing with #256 first which will take substantial effort. So I'd prefer to leave this PR open as is until I'm back.

I'd personally prefer for this to be merged so that I can upgrade to the latest commit even if there's no release yet. But up to you!

2021-11-17 13:56 UTC, emersion commented
Gentle ping

2022-03-21 09:26 UTC, emersion commented
@nhooyr, any chance to get this merged?

2023-02-18 17:41 UTC, emersion commented
Hi, any news about this?

2023-03-07 15:14 UTC, nhooyr requested changes
Will get this merged in after #256

2023-03-07 15:14 UTC, nhooyr commented on write.go
> +		return 0, errClosed
These two are separate errors and should remain. They aren't the same as `net.ErrClosed`.

2023-03-07 15:14 UTC, nhooyr commented on write.go
> +		return errClosed
.

2023-03-07 15:17 UTC, emersion commented
Hm, why is that? `net.Conn` returns `net.ErrClosed` when attempting to write or close an already-closed connection.

2023-03-07 15:21 UTC, emersion commented
Ah, I see, that makes sense! Fixed.

2023-03-22 20:14 UTC, rslobodian commented
+1 to this PR :)

2023-08-25 13:12 UTC, AuroraTea commented
Can this thing go any further?
Really needs it.
At least the original error should be exported.
😥

2023-10-13 05:19 UTC, nhooyr approved these changes

2023-10-13 05:23 UTC, merged

2023-10-13 05:23 UTC, nhooyr commented
Sorry for the delays, thanks @emersion