Fix dial panic when ctx is nil
nhooyr/websocket pull request #365
Opened 2023-01-30 13:09 UTC by guseggert

When the ctx is nil, http.NewRequestWithContext returns a "net/http: nil Context" error and a nil request. In this case, the dial function panics because it assumes the req is never nil. This checks the returning error and returns it, so that callers get an error instead of a panic in that scenario.

2023-03-07 14:48 UTC, nhooyr requested changes
Thanks @guseggert

2023-03-07 14:48 UTC, nhooyr commented on dial.go
> +		return nil, fmt.Errorf("failed to build HTTP request: %w", err)
```suggestion
		return nil, fmt.Errorf("http.NewRequestWithContext failed: %w", err)
```

2023-05-05 18:51 UTC, BigLep commented
@nhooyr : is this going to get merged?

2023-09-16 00:25 UTC, elimisteve commented
LGTM :+1:

2023-10-13 05:28 UTC, nhooyr commented
I'm not sure about this anymore. ctx should never be nil. You should just use `context.Background` instead.

@BigLep @elimisteve why are you guys running into this?

2023-10-13 07:24 UTC, nhooyr commented
Yea there doesn't seem to be a consistent convention on this even in the go stdlib. net.DialContext for example panics on a nil context. https://cs.opensource.google/go/go/+/refs/tags/go1.21.3:src/net/dial.go;l=456

Seems right to me to panic. I'm happy to incorporate the missing err check on `http.NewRequestWithContext` though.

2023-10-13 07:24 UTC, nhooyr approved these changes

2023-10-13 07:25 UTC, merged

2023-10-13 07:25 UTC, nhooyr commented
Thanks @guseggert